[template.environment]
	AIRTABLE_API_KEY="set the airtable api key"
	AIRTABLE_BASE_ID="set the airtable base id"
	AIRTABLE_TABLE_NAME="set the airtable table name"
	AIRTABLE_EMBED_ID="set the airtable embed id"
	CITY="set your city"
	STATE="set your state"

[build]
  publish = "public"
  command = "gatsby build"